# Generated by Django 3.2.12 on 2022-02-12 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20220212_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wotd', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='employees',
            name='score',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='employees.score'),
            preserve_default=False,
        ),
    ]
