# Generated by Django 3.2.12 on 2022-02-12 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employees_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='score',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.score'),
        ),
    ]
