# Generated by Django 3.2.12 on 2022-02-12 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employees_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='score',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.score'),
        ),
        migrations.AlterField(
            model_name='wordofthedayword',
            name='height',
            field=models.IntegerField(default=0),
        ),
    ]
