# Generated by Django 3.2.12 on 2022-02-13 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_score_remaining_letters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='remaining_letters',
        ),
        migrations.AddField(
            model_name='score',
            name='tictactoe',
            field=models.IntegerField(default=0),
        ),
    ]
