# Generated by Django 3.2.12 on 2022-02-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
