# Generated by Django 3.2.12 on 2022-02-13 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_auto_20220213_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employees.game'),
            preserve_default=False,
        ),
    ]
