# Generated by Django 3.2.12 on 2022-02-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_score_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='game',
        ),
        migrations.AddField(
            model_name='score',
            name='game_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='truths',
            field=models.IntegerField(default=0),
        ),
    ]
